name: WEB CI
on: [push]
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npm install @tarojs/cli -g

      - name: 🔥 Deploy
        run: |
          npm run build:h5
          npm run build:docs

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          rm: true
          source: "h5-dist,docs-dist"
          target: "/var/www/html"
