# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npm install @tarojs/cli -g

      - name: 🔥 Deploy
        run: |
          npm run build:h5
          npm run build:docs

      - name: Setup Python
        uses: actions/setup-python@v3.0.0
        with:
          python-version: '3.9'

      - name: Install COSCMD
        run: |
          pip install coscmd
          pip install coscmd -U

      - name: Upload Docs
        uses: sushi-su/setup-object-storage@v1.0.0
        with:
          util-type: coscmd
          secret-id: ${{ secrets.SECRET_ID }}
          secret-key: ${{ secrets.SECRET_KEY }}
          bucketname-appid: ${{ secrets.BUCKET }}
          region: ${{ secrets.REGION }}

      - run: coscmd upload docs-dist /

      - name: Upload H5
        uses: sushi-su/setup-object-storage@v1.0.0
        with:
          util-type: coscmd
          secret-id: ${{ secrets.SECRET_ID }}
          secret-key: ${{ secrets.SECRET_KEY }}
          bucketname-appid: ${{ secrets.H5_BUCKET }}
          region: ${{ secrets.REGION }}

      - run: coscmd upload dist /
